### ISSUE TITLE
STA 518 Project Comments

### ISSUE THREAD

**Issue by lcadagin** [arepesh/Final-Project#1]
If it is true that women are choosing to have children later in life, it would be interesting to also explore if the number of children with chromosomal problems (like Down Syndrome) are on the rise.

It would also be interesting to explore if later pregnancy is associated with higher education or higher income.  If the data is available, you could also explore if the trend of mother ages holds for other countries in the world.

**Comment by LeviRosendall** [comment]
Another thing that would be interesting to look at is if states with higher religious populations are having children earlier. Maybe look at states in the south, like Alabama, Mississippi, etc, and somewhere like Utah. This would simply be finding a dataset on religion by state and merging it with your current dataset. 

I come from a religious background, and I know in my circles that people tend to have children earlier, and Im not sure if that is specific to my situation or if it is a broader trend.

**Comment by farasatm** [comment]
Seems like very interesting topic, maybe if possible provide a little description about the data variables.

**Comment by coourtneyrose** [comment]
This is an interesting topic. Do you have access to any other variables to analyze whether there's a relationship to age of first pregnancy? I would be interesting in variables like different locations, red/blue states, distance to the nearest hospital, etc.

**Comment by elaynast** [comment]
I was going to say something similar to Luke that it may be interesting to see what type of pregnancy complications or birth defects are correlated with older mothers. Another way you could also look at this if you were looking for more could be looking at is if they used any fertility treatments (for example IVF) and how common those are in older mothers compared to younger as well. This seems like an interesting project though!

**Comment by simonsab** [comment]
It may be worthwhile to find additional information on gravidity & parity rates as well. Knowing how many times they've gotten pregnant in the past or if they have given birth may weigh into your research question. It will also allow you to look at current pregnancy rates and determine if the women pregnant currently at an older age are experiencing their first pregnancy (ie waited to have children) or have been pregnant many times (ie struggled to have a full-term pregnancy but have been trying since they were younger) or are pregnant with their 2nd, 3rd, etc child.

**Comment by nash-meg** [comment]
I'm not sure if this data would be available, but another variable aside of the already mentioned ones (religion, politics, complications, etc) could be how old their mother was when they were born. So you could see if people who were born to teen/younger mothers also had children earlier or if they were actually more likely to wait, etc. I would definitely look at at least two variables our classmates mentioned though to give more reasoning to your claim!

**Comment by lindsaybandyk** [comment]
i think this topic is really interesting! I think that you could also look at family history and see if that affected when they chose to have a child themselves.
